package more_table;
/*
 * Zachary Moncur
 * 9/10
 */
public class Ascii_art {

	public static void main(String[] args) {
		// print a single line
				System.out.println("HH  HH\tIIIIII");
				System.out.println("HH  HH\t  II");
				System.out.println("HHHHHH\t  II");
				System.out.println("HH  HH\t  II");
				System.out.println("HH  HH\tIIIIII");
				System.out.println();
				System.out.println("------  __@");
				System.out.println("----- _`<,_\\");
				System.out.println("---- (*)/ (*)");
				System.out.println("~~~~~~~~~~~~~~");
				System.out.println();
				System.out.println(" __");
				System.out.println("( 0>");
				System.out.println("///\\");
				System.out.println("\\v_/_");
				System.out.println();
				System.out.println("  ____   ____  __ __   ____      ____ _____     _____  __ __  ____  \r\n" + 
						" |    | /    ||  |  | /    |    |    / ___/    |     ||  |  ||    \\ \r\n" + 
						" |__  ||  o  ||  |  ||  o  |     |  (   \\_     |   __||  |  ||  _  |\r\n" + 
						" __|  ||     ||  |  ||     |     |  |\\__  |    |  |_  |  |  ||  |  |\r\n" + 
						"/  |  ||  _  ||  :  ||  _  |     |  |/  \\ |    |   _] |  :  ||  |  |\r\n" + 
						"\\  `  ||  |  | \\   / |  |  |     |  |\\    |    |  |   |     ||  |  |\r\n" + 
						" \\____j|__|__|  \\_/  |__|__|    |____|\\___|    |__|    \\__,_||__|__|");
				System.out.println();
				System.out.println("                              .',,,,'''......................................''''',,,,,;;;,;;,;;;;;;;;;;;;;;;;;,,,,;;;;,,,,,;;;,,,,;;;;;:;;;,,,,,,,,;;::;,,;;;;;;;,,;;,,;;;;;;;;:::;;,,;;;;;;;;::::::::::;;:::;;;;;;::::::;..                             \r\n" + 
						"...............................',,'''''''..'.................................''''''',;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;:::;;;;;;;;;;;:;''',,',,;;;;;;'';;;;;;;;::::,',;;;;;;;;:;;:::::;:::::::;;;;:::::::;...............................\r\n" + 
						"...............................',,'..'''...................................'.',',,,,,,,;;,,,;;;;;;;;;;;;;,;;;;;;;;;,;;:;,,;;;;;;;;,,;;;;:::::::::::;:::;,,,,;',,;::::;'';;:;;:;;;;;;,;::::::::::::::::::::::::::::::::::::;...............................\r\n" + 
						"...............................,,,'...'.....................................'',,,;,,,'',,,;;;::;;;;;:;;;,,;;;:::::;,,;;;,,,,;;;;;;::::::;:::::::::::c:::::::;:::::::::,',::::;;;;;;;;:c:::::::::cc::::::::::::::::::::::cc:'..............................\r\n" + 
						"...............................,,,,,....''.................................''',,,,;,,;,;:;;;;;;::;;:::;,,:cc:::::::::;;;;,,;:::::;;;::::::::::::c::ccc::::::::::::::::;;;::::::;;;;:::::::::::::ccccc:::::cc::c::cc:cc:::c:'..............................\r\n" + 
						"...............................,,,,'..''....''.'''.........................'',,,,;;,,;;;:::;;,;;;;;;::;;:cddc::::::::;;,,,,,;;;;:;,;;:::::::::::::::::::::::::::::::::::::::::::::cccc:::::::::::::::cccc::::ccccccccccc:c:,..............................\r\n" + 
						"...............................,;,,,'......',''''.........................',,,,;::;,,;;:::c:;;:;;;:::::::cdko::::::::;;,;,,;;;;;;,,::::;;::::::::::::::::::::::c::c:::c::::::::::::ccc::cc:::c::c:::::cccc:::::::ccccccccc:'..............................\r\n" + 
						"...............................,,,''''.........''.........................',;,,;;;,,;:;;;::::;::;;;;:::;:cokxc::::::;;;;;;;;;;;:;;;;:;,;;;:c::::::::::::::::::c::::cc:cc::::c:::::c:ccc::::c::cc::ccc::::ccccc::c::ccclcccc,..............................\r\n" + 
						"...............................,'''''....''................................',,,,,;;;;,;;::;;:;;;;;;:;;,;:coxOxc:::::;;:;:;;;:;:;;;;;;,,;;:::::::::::::::::::::::::::ccc:::::::::::::::::ccccccccccccccccccccc:::c::::cclcc:'..............................\r\n" + 
						"...............................''''....'''................................''',,,,,;;:;::;;:::;,;:;;;;;,;::ldkkoc::::;,,,;;;;,,,;,,;;,,,,,;;:::::::::::::::::::::::::::::::::::::::::::::::cccc:::::::c::::cccccccccccccc::;'..............................\r\n" + 
						"...............................','..''.....................................',,,,,,;;::;,,,;;;,;;;;;;;;;;:ccldxdl:;::;;;,',,,,,,,,,;;;;,,,',;;;::::::::;;;:::::::::::::::::::::::::::::::::::c::cccc:::cccccc:::::::ccccccc:'..............................\r\n" + 
						"..........................................................................''''',,,,,;,,;,,;;,;;;,,,,;;;;:cccclol;,;;;;;;,,,,,;,'',,,,,;,,',;;;;;;::::;;;;;::;;;::;;;:::::;;;::::::::::cc:::::::::::cc:::::cc::::::::::::cc;...............................\r\n" + 
						".............................................................................,'''''',,',,,,,,,,;;;,,,,;;;:::::cc,.'',;;;;,,,,,,''''',,,,,,;;,',;cool:;;;;;;;;;;;;;;;;::;;;;;;;;;;;;::::::;;::;:;::::::;;;;::::::::::::::::;...............................\r\n" + 
						"                        ..  ....'............................................',,,,,'',,','''''',;,,,',;;;;::::::;,,,;;;;,,'''',,,,'.'''',,,,;;:ldxxo:;;;;;;;;;;;;;;;;;;;;;;;;;:::;;;;:;;;;;;;;::::;;;;;;;;;:::;;;;;;::::::,.... ....                      \r\n" + 
						"                            ..................................................',,'',,,'',,,,'',,,,',,'',;;::c::cccc:::clc;;;;,;;;;,,''',;;;:clodxxoc;,,,,;,;;;;;;;,;;;;;;;;:;;;;;;;;;;;;;;;;;;;::::::::::::::::;;;::::::::,..                             \r\n" + 
						"                            ................................................'.''',,,,,,,,,,,''''',,',,'.,;::cc:clllccldxxddoccclc:;;;,,;:clodxdddoc;,,',;;;;;;;;;;;;;;;;;;;:;;;;;;;;;::::;;;;;;;::::::c:::::::::::::;:::::;..                             \r\n" + 
						"                            .................................................'''',,,,,,;,'''',''',,'..'',::::::cllllodxkOOkdoloodolc:::clodxxxxxdl:;;,,;;;;;;;;;;;;;;;:;;;;::;;;;::::::::::;:::::::;;::::;;;::;::::;::::::;..                             \r\n" + 
						"....................... ..  ..................................................'''',,',',,,,,,,,,,,,'..';::::ccllooodxxkOOOkdooooodol::coodddxxxdoc,'',,,;;;;;;;;;;;;;;::;;;::::::::::;:;::::::::::::::;;::::::::::::::::::,.... ..........................\r\n" + 
						"..........................................................................','..''',,',,,'',,'',,,,',;,,;::cccoxdlodxkkOOOOkdolodoolccloddoodxxxdc,,'''',;;;;;;;;::::;;:;;;:::::cc:::::;;;:::::::::::::::::::::::::::::::::;...............................\r\n" + 
						".........................................................................','','''',,,,,,',,,',,,,,'',;::ccccloddodxkkOO0000koloxddocloddddodxxkx:',;;'';;,;;;::::::::::::::::::ccc:::::::::::c::::::::::::::::c::ccc:::::c:...............................\r\n" + 
						"..................................''.....................................','',,,,,',,,,,,;;;;,',,'',;:::cccclllodxxkkkOOOKKOxxddxxoooddddddodxxdl;,;;;,,,';:::::::::::::::c:::ccc:::::c:::::c::c::::::::ccccc:cccccccccccc:,..............................\r\n" + 
						"...........................................................................'''',;,,,,,;;;;;;:,..'.',;:cccc:;;:cclodxkOOOOO0OOOkxxdoddodxxdddddlc::;;;:;;;;::::::::::::::;:::;;cccccc:c:ccccccccccccc::::ccc:cc:::ccccccccc:,..............................\r\n" + 
						".........................................................................''.','';;,,,;,,,;;;,,,,;,'';ccllc:,'';:coxkkOOOOOOOOOOOkxdddodxxddxxlcc:;,;:;;;,;::::::::,;:cc:,,::;;:ccccccccc:::cccccclccccccccccccccc:ccccccccc,..............................\r\n" + 
						"............................................................................'',,,;:;;;;;,,,,,,,,;;;,;clooolcc:;;:ldkkOOOkxxxxkkkkkxkxdxkkxxxdcc::;,;::;,;;;;;;;;;::::cc::::c:::ccccccccccccccccccccccccccccccccccccccccccc:'..............................\r\n" + 
						".............................................................................',;;,;;,,;,;,,,,,;;;,:::coddddolcc:clxkOOOxo:;;:cldkkkkxxkkxddxdc:;,,;,,;;:::;;::;;::::ccccc:ccccc::cc:::::cccccc:cccccccccccccccccllcccccccc:'..............................\r\n" + 
						"........................................................................','.,;,',,,,,;,,,,,,'',;,,,,:loddodddollcldkOOOkl:;'',;cdkkkkxxxxxxko:,'.''',;::::::;;,,::cc:::ccccc::c::cccccccccccccccccc:c:cccccccccccccccccccc;'..............................\r\n" + 
						".........................................................................,'..'''',,',;,,,'.','.',,,;:odoododdocccldxkO0Oxddooodxk00Okkxxkkkko:;;;,',;;:;;::::;,;:cc:::::cc::;:cccccccccccccc:cc:::cc:cccccccccccccc::cc::::'..............................\r\n" + 
						"..........................................................................''''..',''''''''.','...'',codooddooolcccoxkO0OkkkkkkkkOKK00OOOO0ko:,;;;;,';;;:;;;;;,;::::;::::::::;;::::::::c::::cc::::::cccc::::::cccccc:::cc::;...............................\r\n" + 
						"............................................................................'......''''''..''','..',codddoddoolc:clodxkOOOOOOOOOO0KKKK00KKOl,',,,,'.,;;;;;;;;;,',,,,::::::;:;',,,;;;:::::ccccc::::::::c:cc:::::::cc:::cc::;...............................\r\n" + 
						"................................................................................'.''''''''''......',:ooodooolll::cccdxxkkkkkkkkkOO00KK0O0Kkc,,'',,'.';;;;;;,'',,,;,,;,,;:,,:;,;;',;;:::::::::c:::cc:::::::::::::::::::::::,...............................\r\n" + 
						"                             .....................................................'''..'''........',:oooddo:;::;;::cdxxxkkOOOOOkO0000K0OOOd:,,'',,'',,,;,,''',;::::;;;,;:;;:::::;;;;;;;:::;;::::::::::::::;:::::::::::::::,..                             \r\n" + 
						"                              ................................................'...'''..''..........,:lddddl;,;;'.'';lodxxkOkkkkkkOO000000Oo,..'.','',,,'..',,,;:;;::::,,:::::::::;::;,,;:;;;;::::::;::::::::::::::::::::::;..                             \r\n" + 
						"                              .................................................'..''.',,,'.........':looddlc:;;'...,:cldxkkxxxxkOOOO0K000kl'.','''''','''';:,',;;;:::;,;;;::::::::::;,,;::::::c::;::::::::::::::::::c:::::;..                             \r\n" + 
						"                             .................................................'''',,';::;'........',:loooddoc:;;,',;:::codxkkkkkOOOO000Okd:,,,;;,''',,,;;;::;,;;;;::;'';;;;;;;,;::::;;::::::::ccc::::::ccc::::::::::::::::,...  ..                        \r\n" + 
						"..............................................................................'',;:cc:::'........';:ccooddxxolccccccllllodxxkkkkxkOO00Okxl;;,,;;;;',;:::;;::::::;;::,',;::::c;.';;;:::ccc:::::::ccc:c::::c::::::::::::::::;...............................\r\n" + 
						".............................................................................,,;::cccc:,........,;:clllddodxxdooloodxkkkkxxxxxxkkkOO00Oxoc:;,;:;;;,;:::::::cc::::::;;::cccccc;''',;:::::::::cc::ccc:::cc::::c::::::c::::::;...............................\r\n" + 
						"............................................................................,:::cccllc,.......',:ccclloooxxxxdxddxxxkkkkkkkkkxkkkkOOOOxoc::;,;:::;;:::::::::cc:;;:::cccc:cccc::;,;::::;;;:::cccccc:::::cccccccc:::::cccccc;'..............................\r\n" + 
						"..........................................................................',::ccccclc:'......,:ccclllooddddxxddxxxkxxxxxkkkkxxxkkOOOOko;;;::::::;;::::::cccc:;::;;:ccc:::cccc:;:::cccccc::;,;cc:::cccc:ccccccccc:ccccccccc:,..............................\r\n" + 
						"........................................................................',;:ccccclllc,......,:ccllooodxxxdxxxxxkxxkkkkkkkkxkkkkkOOOOxl:,',:::c:;;;::;:ccccc:,;:;,;;:cccccccc:::ccccccccccc;;::::,;:ccccccccclccccccccccclc:'..............................\r\n" + 
						".....................................................................''';:cccccllcccc,.....,;:cclodddddddxxkkkxkkkkkkkkkkkkkkOkkOOOkdc:;,,;:c:;,;;;::::::::,;:;'',,;;::c:::cccccccccccccc;,;cccc::cccccccccccccccccccccccc:'..............................\r\n" + 
						".....................................................................',;:ccccclooool:,....';:ccloooodxddxxxkkxxxkkkkkkkkkkkOkkkOOOOko::;,,:::;,'';:::::;,,;,;:::::::cccc;,:cccc:cccccccccc;;:clc;:cccccccccccccccccccccccc:'..............................\r\n" + 
						"....................................................................',;:ccccclccllcc:'....';ccclooodddodxxdxxxxxkkkkkkkkkkkOOOOOOOOkl;''',::;;;:::ccccc:;',,,,;:;;,,;cccc;,;::cccccccccc::;:::cc::cccccccccccccccccccccccc:'..............................\r\n" + 
						".................................................................'..',:cccccclllllcc:'....',:ccloodddooddxxxxxxxxxxxxxkkkkkOOkOOOOkd;',;'.'',,,,;;:::cc:;::::::cc::;,;cc:,,;:::ccccc::;;::::::::;;:ccccccccccc::ccc:cccc:c;...............................\r\n" + 
						"..................................................................',;:cccccclllloolc:'...';;:lllooddooddxxddxxxxxxxxxxkkkkOOkkOOOOko;'.',,',;;;,,;:::;;;::cccc:cccc:;;::;:::::::;,;:;;:::::;,,',;:c:ccc:c::::::::ccccc:;;:;...............................\r\n" + 
						"..................................................................';:cc:::cclllolllc:;,''';::clooodoodddddddxxxxxxxxxkkOkkkOOOOOkOkl;'...,;;;,''',;;;;;;;:::::cccc:,;::::c::::::,.',,,'',;;;;,,;;,;:cc::cc:::::::::::c:,;:;...............................\r\n" + 
						"...................................................................,:::::ccclcllllll::;;;;;:cllooooodooxdodxxxxxxxxxxkkkkkkkOOOOkkd:,'....'''.....''',;;;;::::::;,'';;;:::::::::;,,,,,,,,;;;::::;',:cc:::cc:::::::::::;',c;...............................\r\n" + 
						"                             .....................................';::::::cclclollllcc:::::clloollooodoodddxxxxxxxkkkkkkkkkkkkkOOkl,'...''..''',,,;;,,,,;;;;;;;;;,,,,;;;;;;;;::::::;;;;;,,;:::::,';:::c:::::::::::::::;,;:;...                            \r\n" + 
						"                             .....................................,;::::cccllllllllllcccc:cclllloloooddddxxxxxxxxxxkkkkkkkkkkkkOOxc'.'...''''''',;;;;;,,;;;;;;;::::;;;;;,';;;:::::::::::;',:::::,';::::::::::::::::::,,;c::'.                             \r\n" + 
						"                             .',.................................';;::::cclllllllllollollclloollodooodxxddxxxxxxxxxkxkOOOOOOOOOOko:.......,,'''''',,,;;::::::::::::::::;'';:::::::::::::;,,:::::;,;::::::::::::::::::;,;:::'.                             \r\n" + 
						"                             .',..................................';::::cllllllloolllloolllloloolooddddxddxxxxxxkkkkkkOOOOOOOOOkdl;'..''..,;;;;,'',;;;;::::::::::::::::;,,;;;;;;;::::;,,;;;::::;;:::::cc:c::::cccc::::;;;:;.. ..                          \r\n" + 
						"..............................',..................................,;::::cllloooooooloolloolooooooooddodxxxxxxxxxkkkkkkkkkkkkkkkxo:,...,;,'',;;,'',,;;;;;;;;;,,;;;;;;;;;;;;;;;;:::ccc:,';:::;;;;::ccccccc:cc:::cc:::c:::;;;'...............................\r\n" + 
						"..............................,;...........................'.....;::c:cllclooooooooodoloooooddoooodddxxxxxxxxxxxxkkkOOkkkkOOOkkkd;.....,:;,',,,;:,',;;::::::,';;;,,;;::ccc:;,,:ccccc;,,;:::::ccccccccccc::ccccc::::cc::cc;'...............................\r\n" + 
						"..............................,,...................';,'.........,::cccccoloolooooooooooodooddddoodxxxdxxxdxxkxxkkkkkkkkkkkkkkkxdl;'',''';;;;',::ccc;'',;:;;;;,;;:::::::cccc:;;:ccccc;,:cc:ccccccccccccccccccccccc::ccccccc;...............................\r\n" + 
						"..............................,;...................',;:;'......':ccccclllolooloddodddoddoodxddddddxxddkxxkkkkkkkkkkkkkOkkkkxkkxl;;,.,:;,,;;::;;;:::c:;,:ccccc;,,;;:::::::::,,:ccccc:;,;:::::::cccccccccccccccccc::::::::::;...............................\r\n" + 
						"..............................,;....................,;::,'','..':ccccclollloooodoodddooddoooodoodddxxkxddkkkkkkkkOkkkkkkkkkkkkdc::,',:::;;:c:;'';:;;:;,::ccccc;,',,''',,,;::c:;;:;;:::ccccc:,,:ccccccccccccccccc;;:ccccccc:'..............................\r\n" + 
						"..............................,;'...................';;,'.',;,',:cccclllolooodooooooddodxddodxxodxxdxxxxkkkkkkkkkkkkkkkkkkkkkxoc:;,'',::;,:ccc:,,;;;:::cccc:cc::::::cccccccccc:;;cccccccccc:;:cccccccccccccccccc;;:cccc:::;...............................\r\n" + 
						"..............................;;'....................'......''':ccccclllllooodoooooooddddddddodddddxxxkkkkkkkkkkkkkkkkkkkkkkdll:,;;,,;:::::ccccc;''',::::::;;:ccccc::cccccccc:,,;:cccccccc:;:ccccccccllccccccccccc:;:::cc:,...............................\r\n" + 
						"..............................,;'.............................':ccccllllllloooooolddooddddddddddxxxxdxkxkkkkkkkkkkkkkkkkkkkxlcc:;;,;:;,;:::ccccc:;:::::::::,;ccccccc;,;::ccc:::::;;:cccccc:;:ccccccccccccccccclclccc:,';c:'...............................\r\n" + 
						"..............................,;'.'''.........................';ccccclllllooodddooodddddddoooddddddxxxddxkkxkkkkkkkxxxkxkxdolc:,,;,,::;,;::::cc::;:c::::ccc:,;:ccc:::,,:::::::ccc::;::c:::::ccccccccccccccccccc::::::;,,;:;...............................\r\n" + 
						"..............................,;'.............................';ccccccllllooodoooooloooodddooodxxxxxddxxxxxxxxxxxxxxxxxxdddl::,..',;:;''',;;;;;,,,;::cc:::::;,;::;,;::;;::ccccccc:;;:cc::::cccccccccccccccc:::::::::c:;;::;...............................\r\n" + 
						"..............................';'..............................,:c:cccclloooodooooolodoooddooooododddxxxxdodxxdoddddodddddoc;;'....''',;;,;;;:;;;;,;::::c:::,,,,;;;:cc:;,;cccc::;'.,:c:cccccccccccccccccc:;;;::cccc::;;:cc;...............................\r\n" + 
						"...............................,......''.......................';:::cllclllloooloolloollllloodddddoddodxdodxdddddooooodoodoc,'...''..,;;::::::;,;:;',;;;;;;;;,,;:::ccc::,',;:;;;;,,,,::ccccccccccc::::cc:,,;::ccccc::;,:cc;...............................\r\n" + 
						"                             ..'.......''.......................,::::ccllccllllollllllollolllloooddoddooddxxxxdooooodooolol;'....';,',;:::::::,';::;;;;;;;;,,;;;:::c::c:,',;;;:;;;:;,,:cccccccccc:::::cc:;;;;;;;::;:;;;;,,'....                           \r\n" + 
						"                             ...................................';:::::clccclllooolllllllllllclooooodooddxxxxdoloooooolollc,...''',;,';;;;;;;;,'';::::::::;,,::;'',:::;,'';::::::::;,;:::::::::c:::::::cc::;;;;;;;''''',,,'...                            \r\n" + 
						"                             ....................'...............';::::ccccclllloolllllllllllllooooooodxxxdddollllloooolll:,...','',,'',,,;;;;,,,,;;;;;:;;;;;:::,',;;;;,,,,;:::::::;;:::::::::::::::c::::::::::;;;;,,,,;;;,..                             \r\n" + 
						"                            .....................'................,::::::cccccclllllllllllllcllloooodddxddddocccccclloolol:,....'''';'.,,,;,',;::;;;;;;;;;;;;:::;;::::::::;,,,;:::;;:::::::::::::ccc:cc:::::::;;;:::::::::;...                            \r\n" + 
						"..................................'''.............................';c:::::::cccclccllllllcclcccloolddoodddddoc::::ccllllol:'.......',',;;;;,'';:::::::;;;:;;;;;;;:::::::::::,,;::;::::::::::::::ccccccc:::::;;;::c::c::ccc;...............................\r\n" + 
						"..................................'''..............................,:ccc:::::ccccccllllccllllcclooooodddddddo:,,;::clododo;.....'''.',;;;;;;,';;:::::c:;:::::c:;,;::cc:cc:c:;;::::::::cc:c::::ccccccccc:::::;;:::::cc:cc:c;...............................\r\n" + 
						"...............................''..''.......................''.....',;:ccccc::cccccccccccccccccloooooodxddxdc,..;:ccllddol;......',,,,;::::;,,;;::::;;;;:ccccccc;;::c::cccc:;;ccc::ccccccc::c::ccccccccccccc:::c:::;;:cc::;...............................\r\n" + 
						"....................................'',''...................';,......',;;:ccccccccccccccccccccccllooodddxxxdc,..,:ccloddol;....''..,;,;:::;;,;::;;;:;,,::ccccc:::::::::::::::ccccccccccccccccccccccccccccccc::cccc:,;:cccc:'..............................\r\n" + 
						".....................................',;,'...................'..........'',;:cccccccccclccccccccclodddddxxxoc,'.':ccloddol;'.......',,,;::,';:cc;;:::c:;;;;:::;,:ccccccccccccccccccccccccccccccccccccccccccccccccc;;ccccccc;..............................\r\n" + 
						"...................................','.'',,'...............................',::ccccccccccccc::::cclodddddxdo:'..':ccloodoc;',,,'..'.',,;:::::cc:;;::::cc:,::::;;:cccccccccccccccccccccccllcccccccccccccclc:cccccccc::cccccc;..............................\r\n" + 
						"...............................',,''','',;;,'..........................''''.''',clcccccccc:;,'';:ccclooodxxd:'...;ccloddoc;,;;;;,,,'''''',,;::c:;;:c::cc:,:cccc:;:ccccccccclccccccccccccccccccccccccccccccccc:clccc:;cccccc,..............................\r\n" + 
						"...............................'',,',,,,,,,;,'....',,'','.............';;;,'...';cccclccc:;,...';:cllododdxxl'..';cccloool;'',;::;,,,,,'...,;;::,;::c::c;,:cccc:;;cccccclccccclccccccccccccccccccccccccccccc::ccccccc:,;::;'..............................\r\n" + 
						"...............................,,,,,,,,,,,,''......';,';::,.........'',;;,,,'..';:c::ccc:::;'....,:cloooddooc,...,:cclooll;,,',;:::::;''..',,',,',:::::;,,::::::;:ccccccccccccccccccccccccccccccccccccccccccccccccc::::::c:,..............................\r\n" + 
						"...............................,,;,....'',;,...,'..';;;;::;;;;;,'...';,,,,,;,'..';::::c:::::,....';cclllodddl,...':ccloolc::;,,,::::::;,'..'..'','',;:::;;;;;;::::::ccccccccccccccccccccccc:cccccccccccccccccc:cccc;;:ccccc,..............................\r\n" + 
						"...............................,,'.......'.''.,;,,,;;;;;;;;;;::;;,,,,,,,',,,''''..';::::::::;'..',;::cllodool;...';::cloolcc::;,,;;;;:::;;,'....''',;;::::;;;;;;:::::ccc:::cccccccccccc::::::ccc:cc::::::cccc:::cc:;;::cccc,..............................\r\n" + 
						"...............................''........',,,,;;,',,;;;;,,,;,,,,;;;;'....'''.......,::::::::;'.',;;::ccloooll,....,::cclllc::::,,;;,;;;;:::;,''''''...,;;;:::;;;:::::::::::::ccc::::::::::::::::cc::::::::clc:cc:::::clolcc,..............................\r\n" + 
						".......................   ..................',;;;,'''',,,'..'',',,;;'...............'',::::;,...',;;::cloolll:'....,::cccccccc:;',;;;;;;;;;;;;;;,,,'......';;;;;;::::;::::::::c:::::::::::::::::c:::::cccllc;,::::::::ccc::'...  .........................\r\n" + 
						"                             .................,;;;,..........'..',,'...................';;,'..'....';::clllllc;,...';:::::::cc:;',;;,,;;;;;;;;;;;;,;,,,'....''',;:::::;;;::::c::::::::::::::::::::::ccccccc:;;;::::::::::;,...                            \r\n" + 
						"                              .................,;;;'........'....'''''........','............',,'...,::clllllc::;....';:::::::;,..',,,;;;;;;;,,,,',,,;;;;'''...''',;:;;;;;::::::::::::::::::ccc::ccccc:c:::::::;;::::::;,;;..                             \r\n" + 
						"                              ................'',;;,.......,,'.'''',;;,.......';,'............''..'.';:cclllccll:,.....'',;;,''.....'',;;;;;;,,',''',,,,,,;;,,,'...''',;:::;::::::::::::::::cccccccc::c:::;;::::::ccc::;,;:'.                             \r\n" + 
						"                          .................,;;,'',;;,''....',''',',;;;,........'''................''';:::::ccllcc;........'...........'',;;;;;,,;;,,;;;,,,,;::;;,''''...',;;;::::::::::::::::ccc:::::::::;::::cccccc::;::::'...                           \r\n" + 
						"............................................',''.';;;;,'....',',,,,;;;,,'...........................',;:cccccllcc:'......'.........'....',,;;;;;;;;;;;;;;;,,,;;::::::,'''',,;;;::::c::ccccc::cc::::::::::::::;:cccc::;;::::,..............................\r\n" + 
						".................................................',;;:;;,.''',,,,;;;:::::,'............................,::cccccc:,'.....,;,'''............',;;;;;:::::;;::;;,,;,;::::::::::;,';;,;::cccccccc::cc::::c::ccccc:::cccccc::ccc:,..............................\r\n" + 
						"...................................................,:::::,',,',;;,;:cccccc;............................',;::ccc:,......';cc:;;,''...',,'','',,',,,;:::::;;;:::;,',;:::c:::c:::;,,,;;:ccccccccccccccccclllccccccccccccccccc:'..............................\r\n" + 
						"...................................................',;,;;:::;,,;;;;::ccccc:,'................''''.....,::;;::::,'''...';cccccc:;;,',,,,,,,,,,',,'.',::::::::::::;,,;::::::::::::::;,;::::cccccccccccclolccccccccccccllcccc;'..............................\r\n" + 
						"..............................,:;'''''................'',;:cc:;,,,,;:::;::;,''..'.'..''.....';::;,'.'',:c::::cc:;;:,',;:ccccccccccc:;;;,',;,,,,,'.',;;::::c:::::::::::;;:c::::::cccc:::::::ccccccccccclcclllcccccclllllccc:,..............................\r\n" + 
						"..............................':ccccc:;'.................',;::::,'.',;;'''''...',''''''..''';cccc::c:,',;;;'':cccccc::::cc:cccccccclc::,''''',,''..''',,;:::cc:::::::::::::::;;::cc::::::::::c:::ccccccccclooolloloollccccc;..............................\r\n" + 
						"..............................':cccccc:,..............','..'',;:;'...'.....'''.'''','''','',:lccccccc:,''''..':ccccccccccccc:::cccccc:::;,''',,,,''''''',;::cc:::::::;;:::::;,,,;::::::::ccc:cccc:::;:cccclooolloollllc:clc;..............................\r\n" + 
						"..............................';::cccccc:;'''.........','......'..'...........'....''',;;;;;:cccccccccc;'...',;cccccccccccccccccc:::;,;:::;,,,'',,;''''',;,;:::c::::::::::;;;;;;,,,::::c::ccccccc:::::::::::cllcclloolccccc;..............................\r\n" + 
						"...............................;:;::ccccc:,'.......','...............''...........'..'',;,,;:ccccccccccc:,....',::ccclddoc;;ccccc:cc;,;c:;;:c:;,''''..''''..''',;::::::::::;,,,,,,;::;:::::::::::::::c:::::::::;;;;:cccclcc,..............................\r\n" + 
						"...............................,;;;;:::ccc;...........................,;,.............','',,;:ccccllccccc;'.....,:c:cloodo;',;;ccc:;;;::;',:::::;'..',''''......'';::c::::::;;;,'',;;;;;;,;;;;:;;;,,;::::c:::::;;;;,'',;:c:'..............................\r\n" + 
						"...............................,;;;;;;;;:;'............................';;,,,,'........'..''',:clooddooolc;'....,:c::cclll:;;;;;;;;;;:;;''.';;:::;'......'.........'';:::::c:::;;,'.',;;;;;;;;;;;;,;;;;;;:::::::::::;,'''''...............................\r\n" + 
						"...............................;::::;;,;;,'..............................'',;:;;,.............,:llclllllooc;,'....'..',;ccc::::::;;::::;,,,''';;::;;,;,'.',,,'.',,'....',;::::::::;,,'...,;;:::;;;;;;;,,''',;;::::::::;,,,'...............................\r\n" + 
						"                             .'::::::;:;;,,''...............................';;::,'...........'''',;:;;:llc::;;,'......',;::::ccc::cccc:;;;,.';;;::cc::,'',;;;'',;;,....';;;;::::cclc:;,....,;:::::::;;;,,'...',;::::::ccc:'..                            \r\n" + 
						"                             .,:cc::::::;;;,'.........................'........',::,''.............''''',;::ccc:;:;,'....'',;::cccc:cccc:;,,'';;;:::::;'',;;;:;;,,;;;,'..'',;cllcccllool:,''''',;;::::::::;;,,'..,;::clllll,.                             \r\n" + 
						"                             .,ccccccc:::;'...........................';,,,'','..'','''..................',,:::cclc:;,,,'...,;:lolc::cllc:;;;,,;;;;:::;'',;:::::;;;::::;,''.,:dkkxddoccccccllc::c::::;;:::cllolc:;;;;:::ccl,.                             \r\n" + 
						"                             .,ccllllllllc'......................''...';:;;;,,;;'..........'................',:cccc::::c:;;'',:llccccokxocccc:;;:;,;::c:;;:cccc:ccccccccc:'...cOKXKOxo:,',cldxkkxdoolccllllloxO0Oxolc;,;;;c,.  .                          \r\n" + 
						"..............................,:::lolollll,....................',;;,;;,;;,,;;,;:::;'.........''.........''....,;:::ccccccllc;,;;,,:clx0KOddolcc;::;',:ccc:ccccccccccccccc:,...'cxO000Kkl,.',;codxkOOkxxkkOkxxxk0KK0Oxl:;,;;...............................\r\n" + 
						"..............................';,,;:::;,,,..'...................,;::::cll:;::;,,;;;,''''.....','..''''...'',;,',;;;ccccccoddol:,,,;clxO0Okkkdol:;::;,;:cccllcccccclooollcc;'...',cooxOKKOo:'',;;:lodxkkxxO0OOOkO0KKOOko:::,...............................\r\n" + 
						"................................,,,,'''''....''...............''',;:::lool::::;;,''',;;:;''''....',;;,,,',;;;;,,,;;:;;;:coxxkkxolc:cldxkxxxxkkkdlcc:;,,;cloooooooodxkkkxoc;,,,'.....':oOXN0dlcc:;,,;:looloxkk0K0000O00Oolc;...............................\r\n" + 
						"...............................,'';,'',;:;,,'','.',,,''........''',;::ccc:;::::;',;,'',;;;;;;,''...',,;cc:;,',,,,,,;,..;clodkOkxdxdccclolooldk0Oolc::::;:clodxxxdodddkkkxoc;,''''',,'';cdKXKkddddool:;:::;:codxxkOO00000Od:'..............................\r\n" + 
						"...............................,,',;,;:::ccc:;;,,,,,,;,'''.......'',:c:,''',,;:;,,,,,,,;;;;;::c:,''''',;cllc::c:;;;;,''';lcldxkxooxollllcclloxxxdololc::::loxkkkkxxxxO0Okxoc;,,,'',,',;clx0K0kxxkxxxxdollc:ccclolldkOKK0KKk:..............................\r\n" + 
						"...............................''''''',,;;::::;::;,,,,;;;,'..'''.'.'''''',,,;;::,'''''',,,',:cccc:;,,,'';clllllllllc,',;:cllllodollllllllccdkxooodxxxolcccclldxkOOOkxk000Okdolc;,',;:;;:clodO0kxkkkkkkkkkxxxdolllc:coxkO0K0l..............................\r\n" + 
						"...............................'.'',,,,,,;:;;:::,;::cccllc:,,::;''.,,..',,'',;;;;,;,''',,,;ccclodolcc:;'',:clcclllllcc::::cllllcclccllodoc:ldOOxolodkkdllc:clooodk00OO000Okkkkdlc;;;;;;;;;cld0KOkkkkkkkkkkkkkOkkkdo:;;coxkkc..............................\r\n" + 
						"..............................',,'.''',',;::;;,'',;:ccldxdddddolc:,''''''''';,,;,,;;,,,'',:ccllodddxxxdoc::clcccclddolccc::clcc:;:;;clooool::dOOxc:ldkkdoc;;codddxk0OOO00OkkkOOkxoc;;,,;,;:clx00OkkOkOOkkkOOOOO0O00Oxdl:clo;..............................\r\n" + 
						"...............................,;,..'''''''',,,',;::clldxkkkkkkxoc:::;;,'',;;,''''';;;;,';:cccloodxkOOO0Okxxolccccldxxolllcclllccc;;cllllllcccclooc::ldxdlc;:coxkddkkkO000OOO000OOkdlc:,',,:cldOK0OkOOOOOOOOO0OO000KKK0kdl;...............................\r\n" + 
						"...............................,,...','..''..',,,,,,;cllodkkOO0Okdccc:,;::ccc:,....',,,'';:cccllooodxO0000K0OOko:,;cloolcllcllllllcccllllllllc:cccc;';coxxoc;;:okkddxdkXXK0OO0000000kkxoc;,;:clxKX0kkOO0OOkkOO000KXXKXXX0Od;..............................\r\n" + 
						"...............................''';,'....''....,''',;:cccloooddxkxdlccclddxxdl;',''..,'.,:::::ccloddxkOO0KKKKKKOxoccccccccccllollolllcllclllllllc;,'.',:oxxoc::lx0kodxOKXX0O000000O0KOkxdolc:;clkXNKOkOOOOOOOOO000KXXXXXXN0:..............................\r\n" + 
						"...............................''''..''.............,;::::loolclllloodxxxxdoo:,,,'''..',,;::::::cloddxkOO00KKKKK00Okxoc;,::ccclclddodddddxddoooll:;'...,clddlcccok0xlldk0KXK0O00000000Okkkkkdlcclx0NXK0OkOOO000OO00KKKXXXX0c..............................\r\n" + 
						"                         ..  ..',,,,''''..''.....'....,;;;;cddc:cldxdoddddlcc;''''''..',,,;::::::cclodxkOO0KKKKKKKXKKOko:;,;:::cclllodxkkkxkkxxdlc:;'...';cdlccccokkl;:lxOXNXKKXKXXK000000K0OkdlcldOXNX0OkOO0KK00000KKXXXXO:..                            \r\n" + 
						"                             ..'',;;;,,''''..........';;;;;:odoooxOOxddoooccc:,''.....',;;,;::::ccccloodkOO0KKKKKXXKXNXKOdc:;,,;ccccccodxxkkOOkkxollc;,'.',:cllclcokd:;:coOKXXKNNXKXX000000000Oxl:cd0NWNK0OOO000KKKKKKXXXX0:..                            \r\n" + 
						"                             ..''''''',,;;,.''....,,,;::::cclodxxxxkkxddoooolc:,''..'.',;;,,;::::ccccclodxxOOO0KKXXXXXXNNKOkdollc;,;cccclodxkkkkkxdxxddolccccllllclxkoccccox0XXXXK0KXXXXXXKKKKK0xc:cd0NWWXK0OO0000KKKXXXXX0c..                            \r\n" + 
						"                             ..',......'';;,,'..',::c::::cllllloodddxdoldxxxdooc;;,;;,',;;,',::::ccccccclodxkxk0KKXXXXXNNNXXXXX0xo:;;;:c:ccloodxddxkOOOOOkkxddooolcoxxdddlccdOKXK0OOKXKXNNXXXKKK0kdlcd0NWWNXK00OO000KXXXXXO:...                           \r\n" + 
						"...............................''........',;;'..,;;:c:ccccllllclooooodoldodxxxxxolc::;,,;;,'';:::ccccccccodddxkO0KKKXXXXXNNNNNNNNX0xl::;:::ccclloxxkOO0000OOOOOOkddodkkOOOdlcokXXKkdOK00KKXXXXKKXX0xccxKNWWWNK00000KKKXXXXO:..............................\r\n" + 
						"...............................,;;,,''.....',;,,;,;cllcclllcccccoooolooolcodddxxxdol:;;;;,,'.';;:cccclllllollodkkO0KKKKXXXXNNNNNNNNXKOxolc:::ccccoddxkkkOOOOO000OOOO00OO0KKOxxkOKX0dx0KOxxkOKKKK0OOxocok0KKK0OOOOOOOOOOO0XOc..............................\r\n" + 
						"..............................':ccc:;,',;,,',;:::;;codooodoccc:cclooooolcccccldxkkkxdlc::;'''..,;cllcclooolllloodxxO000KKKKKXXNNNNNNNWWNXOdlcc::cccclloodkOOOO0000O0XK000KKXXX0xkKKxdOK0xolodxkxdlc:::codxdddoolllloodddkKOc..............................\r\n" + 
						"..............................:ddll;';::::::::;:cclclddxxxdlccccccldoooolc:ccodxxkkkkxolc:,'....';:clllllolllloddddxkkO0KKXXXXXNNXNWWWWWWWNXOoc:cccclllllldkkkkO00000KK00KKKKXNKOKKkoxKXKkooooooo:,',;:okO00OkdoooodkkkkO0Ol'.............................\r\n" + 
						"..............................:xkxocclccccccc:;:clllloxkkkxoccccloooddoooc,;cloodxxkkkkdlc:,'''..';::clloollooooodddddxOO0KKXXXXXXXNNNNNWWWWWNKkdocllccclldxxk0OOOkkkO0000000XNXKOK0dd0NNKkxO00Okl,'';:ldOKXXK000000OOkOO0kc'.............................\r\n" + 
						"..............................;oo::lxkxoc:,',;:ccccllodO0Okdlcccloodddddoc::cloxddxxxxxxolcc:;,''''',;:llloollddooddddddxkO0KKKKKXXXXXXNNWWWWWWWNXK0koooolllodOKKK0kddxxkOOkkOOKKKK0xdOXXXKOkOOOOd:,,:cok0KXXXXXXK0000O00K0l'.............................\r\n" + 
						"..............................';,',ck00ko:,,;;;;;:ccoxO000Odllcclodxxddxdocclllodxdddddoolccc:::,''..',:ccloolooooodoodddxxxkkOKKXXXXXXXXNWWWWWWWWWWNNK0kdoloodO00KKOxdooodolodk0KK0OkkKKKOdoooolc:;,,:ok0KXXXXXNX00O00KKKOl'.............................\r\n" + 
						"...............................'',,:oxxdl;,;ccc;;:coO00KKK0xoooodxkkkxxkxxolcccllllllllllllcc;;;,,,'...',:ccloooollodooooddddxxOKKKKKXXKXXXNNWWWWWWWWWWNNXK0OOxxO000OOOxolllllldxO0000O000xolc:;;,;:::clxOKXKXKKXXK000OO0Ox:..............................\r\n" + 
						"...............................,',;;::cc:;:coolc,':okKKKKK0kxdddxxkxkkkkxxolccccloodooollcccc::;;,,,,'''.',;:clllodooooodooddxdxkOO000KXXKKXNXNNNWWNWWWWWWWNNXXNXXKKKXX0Okdl:cclloxxkO0KK0xlc:,,,;::cclkKOOXXXXXNNXK00OOKKk:..............................\r\n" + 
						"...............................;;',;,;;,',ldxkko;,,ckKKKK0000kxxkkkOkkOOOkxocclodxddoooolcccccc:::;;;;;,''''';:ccloooooololooooodddxOOO0KXKXXXXXXXNWWWWWWWWWWWWMWNWWWWWNXXK0kdlcllllox0000Odl:;,,:clodkKNOx0XK00KXXXK00OKXk:..............................\r\n" + 
						"..............................'::col;,,,,:ok00Kkc;,lxO00OOKKK0OOOOkOOkOOOOkddddxxxxxdoolcccc:::cc::::;;;;;,'.',;:cccooooolloooooddoddxxk0KXXXXXXXXXNNNWWWWWWWMMMWWWWWNWWWNNNNXK00OxollodkOOkoc,';lxOO0KXX0kk0X0OOKXNX0OO0KO:..............................\r\n" + 
						"...............................;clol;;;;;;cxOO0kl,',:lloodO0KKK000OOO00OOOkxxxxxxxxxxdooolccc::::::::::;;;;;,,,,,;;:clclllloooollodooddxkkO00KXXXXKKKXXNNWWWWWMMWWWWWWWWWWWWWWWWWWNK0OOkdoool:;cxOKXXXKK00OO000kk00KXK0000Oc..............................\r\n" + 
						"                          ....':cccccoddc;coooooc:;;;:;::clx0KKKKK0xdk0KKOxdxxkkkxxxxxxxddolc::::::cc:::;;;;;;;,,,'',;:ccclllllloloodooddddxkOO0KKKKKKXXXXNNWWWMMMWWWWWWWWWWWWWWWMMWWWNX0kocldk0XXNNNNKOO0OkO00OOOO00KXK00Ol.....                         \r\n" + 
						"                            ...;ccccloddlcclccccccc::::cc::ldk0KKKOocldxxdodkkkkxxxxxxxxxxdc:::::::::::::::;;;;;;;,,'',::ccccclllollooodddddxxdxkO000KKXXXKXXNNWWWWMWWWWWWWWWWMWWMMMMWWWWNK00XNWNNNNNX0OO00OO00O00OOO0KKKK0l..                            \r\n" + 
						"                             ..,:cccccclccccccccccc;,;:cc:;,;lxOOxl;,,;:c:cdkkkxxddxkkkkkxdooc::c:::::::::::;;;;;;;;;,,;;;:cccclllllllooooooooodddxkkOO0KKK0KKXXXNNWWWWWWWWMMMMMMMMMMMMMMMWWWMWWWWNXK00OO0KKK000KK0OOOO00K0l..                            \r\n" + 
						"                          . ...;::ccc:;:ccccccccccc;',:cl:'.,:ccc;'',,;:ccloxxxdoldkkkOOkkxxxoccc:::::::::::::;;::::::;;,'',;;:cllclllllolllooooodddxddxkOOO0KKKKKXXXNNWWWMMMMMMMMMMMMMMMMMMMMWWWNXK00OkkO000K0KNX0OOkkkkOkc....                          \r\n" + 
						"..............................,cc::c::,;cllccccccc:,',;loc,',:;,,,,,;:cccclodxdcclxOkkkddxkOkdlccc::::::::::::::::::::;;,....',;:ccclolloollllolooodddddxxkkk0000KKKKXXXNWWWMMMMMMMMMMMMMMMMMMMWNXXKOOOOOOkO0KKXNXKK0Okkxkx:..............................\r\n" + 
						"..............................,:cccccc::clcccccc:::;,,,:c;,',::::::;,;:ccclloolcclxkdolclxkOkxdooolc:::cc::::::::;;:;;,.........,;;::cccloloooloooooddddddxxxxkkO0000KKKKXXNNNWWWWMMMMMMMMMMMMWNKO0KkdOX0xxOXX0XNNNK0000kxxc..............................\r\n" + 
						"..............................':cccclcccccc:cccc;,,;:;;,,'',;::::::::;;::ccc::;;:ldo:,;:cxkOOkxxxxxocc:ccc:::::;;;,,''............',,;:clolloooodoooddddoddxxxxxxxxkOO0KKKKKKNWNXNWWMMMMMMMMMMWXxcxKOx00dld0XKkOXXXKKXXXOxd:..............................\r\n" + 
						"..............................,ccccclc::cc::cccc;,;;;;;,,,,;:;,,;:;::::;,;:,'''',coc:loccxOOOOkkkkkxdoccccccc:;,'''''''''''.''''.....',;:clllloooddddododddddxxxxxxxkkkkOOO0KXWWXXNWMMMWWMMMMWWNOod0K0KkoookXKkkXXKKXNNNKOx:..............................\r\n" + 
						"..............................,cllllllllcclllccccc:;,,';:,'',;,,,,',,,;,;;;,,,,,:cccldxddkOOOkkkOOOOkxolcccc:;;,',;,'',,,;,'''''''...''',,;ccllloddddoooddodxdddddxxdxkkkOOOO0XNNNNWWWWMMMMMWNNNN0k0XN0ddxdxKKOOKX0OKXXNNXOc..............................\r\n" + 
						"..............................':ccccllllddolc:;;:;;:;;;;:;,,,:;;;;;;,',,;;;;;;:;;::clodolxkkkkkxkkOOOkxolc;;;:;,',;,,,'''',,,,,,,,'''',;,'',;:ccloooooooooodooooooddodddddxxkkO0XKKXXXNNNWWWNNNNWWNXNXkodxookOxk0K0OOO0KNNKo'.............................\r\n" + 
						"..............................';::::lllldxol:;:::::;;::,:;;,,:;;::;;;,;;;;;::cc:;::cllllllooxkdoodkOOkdoolccc;,,,;,''',,,,',,,,,;:,,,,;::;,,;:::ccclllooodooooodooooolloooooodxdxkO000KKKXXKKXNNNNNWWNKOxdoloxkkOkxdkOkk0XKo'.............................\r\n" + 
						"..............................';;;ccllooollc:::cc:;:::cc:,,;,:c;:cc:;;,,;::;:ccccc:;:cllllllodoodooxkxddollllc::;;;;,',,,;,,,,,,,,;;;:::::;;:c:ccccc::ccclllllloolllllolllllollododxxxk00K0OO0KNNNNWWXKKKK0xddxxkkdodxkxxKKo'.............................\r\n" + 
						"..............................':ccclllllllcccccc::;:cccclcccloc:cdxoccc:cc::cccclc;,;clllooc:codooxkdodxolllllcccccc:,;,,;;;;,,,,,:ccccc::,,:ccccc:;;,'''',,;::ccccccllcllllllllllloxxxkO0KK0O0KXNNWNXKXNNNNKOxddxxxxdoloxxc..............................\r\n" + 
						"..............................':lcc:cclcccc:;cllc;,;:cccclx000xdx000Odlccccccccclc:,,:lloolc:lk00OO0Okkkdlllclllllcccc:;;,,,,,,,,;:ccccccc:,;:ccc:;,,,'''.''''''''',;:ccccccccccccccokOkkOKXNKOO0KXNNXXXNNWWWNKkoldxxdllllo:..............................\r\n" + 
						"..............................'::;,;:ccclllcccclcccldkdllx0XXXK00KKKK0dlllcccccccccc:;:cllclxkOKKkddkkxxdollllccccclllccc::::::::;;:ccc::c:;;:c:::;'..,;,'..........'''';:::::cc::::lx0K0O0KXNX0OO0XXXKKNWWMMMWX0kdoolccccc;..............................\r\n" + 
						"...............................;;,;::cccllclxkkkxxxO0KKOkOXXXXXXKKXXXKxldkO0kolcccccccccccldkkOKKd:cldxxxdddollloddxdoolccccooollcc::::cccc::cc:::;;,;::;'..............'',::cloc:::lx0XNK0OOKXXK0O0KXKKXNWWMMWWWNKOkolllcc,..............................\r\n" + 
						"cccccccccccccccccccccccccccccclddddxxkxxkkxOKNNXXKKXNNNNXXNNNNNNNNNNNX0k0XNWN0kkkkxxkkkxxkkO00KNNOdxkO0K0O00OkkkO0000OOkkkxkO0OOOOkxxxxkkkxxxxxxxxxxxxxxdollloollllllloolldxxkOOkxkxk0XNWNXK0XNNNXKKXXXNNWWWMMMWMWWNX0kOkxxdcccccccccccccccccccccccccccccc\r\n" + 
						"");

	}

}
